/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WebsiteRouteImport } from './routes/_website/route'
import { Route as AdminConsoleRouteImport } from './routes/_admin-console/route'
import { Route as authRouteImport } from './routes/(auth)/route'
import { Route as WebsiteIndexImport } from './routes/_website/index'
import { Route as errors503Import } from './routes/(errors)/503'
import { Route as errors500Import } from './routes/(errors)/500'
import { Route as errors404Import } from './routes/(errors)/404'
import { Route as errors403Import } from './routes/(errors)/403'
import { Route as errors401Import } from './routes/(errors)/401'
import { Route as authSignUpImport } from './routes/(auth)/sign-up'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as authOtpImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordImport } from './routes/(auth)/forgot-password'
import { Route as AdminConsoleSettingsRouteImport } from './routes/_admin-console/settings/route'
import { Route as WebsiteEventIndexImport } from './routes/_website/event/index'
import { Route as WebsiteDreamIndexImport } from './routes/_website/dream/index'
import { Route as WebsiteDonationIndexImport } from './routes/_website/donation/index'
import { Route as WebsiteBlogIndexImport } from './routes/_website/blog/index'
import { Route as WebsiteAboutIndexImport } from './routes/_website/about/index'
import { Route as AdminConsoleUsersIndexImport } from './routes/_admin-console/users/index'
import { Route as AdminConsoleTasksIndexImport } from './routes/_admin-console/tasks/index'
import { Route as AdminConsoleSettingsIndexImport } from './routes/_admin-console/settings/index'
import { Route as AdminConsoleHelpCenterIndexImport } from './routes/_admin-console/help-center/index'
import { Route as AdminConsoleDashboardIndexImport } from './routes/_admin-console/dashboard/index'
import { Route as AdminConsoleChatsIndexImport } from './routes/_admin-console/chats/index'
import { Route as AdminConsoleAppsIndexImport } from './routes/_admin-console/apps/index'
import { Route as authSignUpIndexImport } from './routes/(auth)/sign-up/index'
import { Route as authSignInIndexImport } from './routes/(auth)/sign-in/index'
import { Route as authOtpIndexImport } from './routes/(auth)/otp/index'
import { Route as authForgotPasswordIndexImport } from './routes/(auth)/forgot-password/index'
import { Route as AdminConsoleSettingsNotificationsImport } from './routes/_admin-console/settings/notifications'
import { Route as AdminConsoleSettingsDisplayImport } from './routes/_admin-console/settings/display'
import { Route as AdminConsoleSettingsAppearanceImport } from './routes/_admin-console/settings/appearance'
import { Route as AdminConsoleSettingsAccountImport } from './routes/_admin-console/settings/account'

// Create/Update Routes

const WebsiteRouteRoute = WebsiteRouteImport.update({
  id: '/_website',
  getParentRoute: () => rootRoute,
} as any)

const AdminConsoleRouteRoute = AdminConsoleRouteImport.update({
  id: '/_admin-console',
  getParentRoute: () => rootRoute,
} as any)

const authRouteRoute = authRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const WebsiteIndexRoute = WebsiteIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebsiteRouteRoute,
} as any)

const errors503Route = errors503Import.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRoute,
} as any)

const errors500Route = errors500Import.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const errors404Route = errors404Import.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRoute,
} as any)

const errors403Route = errors403Import.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRoute,
} as any)

const errors401Route = errors401Import.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRoute,
} as any)

const authSignUpRoute = authSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)

const authOtpRoute = authOtpImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => authRouteRoute,
} as any)

const authForgotPasswordRoute = authForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)

const AdminConsoleSettingsRouteRoute = AdminConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminConsoleRouteRoute,
} as any)

const WebsiteEventIndexRoute = WebsiteEventIndexImport.update({
  id: '/event/',
  path: '/event/',
  getParentRoute: () => WebsiteRouteRoute,
} as any)

const WebsiteDreamIndexRoute = WebsiteDreamIndexImport.update({
  id: '/dream/',
  path: '/dream/',
  getParentRoute: () => WebsiteRouteRoute,
} as any)

const WebsiteDonationIndexRoute = WebsiteDonationIndexImport.update({
  id: '/donation/',
  path: '/donation/',
  getParentRoute: () => WebsiteRouteRoute,
} as any)

const WebsiteBlogIndexRoute = WebsiteBlogIndexImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => WebsiteRouteRoute,
} as any)

const WebsiteAboutIndexRoute = WebsiteAboutIndexImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => WebsiteRouteRoute,
} as any)

const AdminConsoleUsersIndexRoute = AdminConsoleUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminConsoleRouteRoute,
} as any)

const AdminConsoleTasksIndexRoute = AdminConsoleTasksIndexImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AdminConsoleRouteRoute,
} as any)

const AdminConsoleSettingsIndexRoute = AdminConsoleSettingsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminConsoleSettingsRouteRoute,
} as any)

const AdminConsoleHelpCenterIndexRoute =
  AdminConsoleHelpCenterIndexImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AdminConsoleRouteRoute,
  } as any)

const AdminConsoleDashboardIndexRoute = AdminConsoleDashboardIndexImport.update(
  {
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AdminConsoleRouteRoute,
  } as any,
)

const AdminConsoleChatsIndexRoute = AdminConsoleChatsIndexImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AdminConsoleRouteRoute,
} as any)

const AdminConsoleAppsIndexRoute = AdminConsoleAppsIndexImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AdminConsoleRouteRoute,
} as any)

const authSignUpIndexRoute = authSignUpIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authSignUpRoute,
} as any)

const authSignInIndexRoute = authSignInIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authSignInRoute,
} as any)

const authOtpIndexRoute = authOtpIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authOtpRoute,
} as any)

const authForgotPasswordIndexRoute = authForgotPasswordIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authForgotPasswordRoute,
} as any)

const AdminConsoleSettingsNotificationsRoute =
  AdminConsoleSettingsNotificationsImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminConsoleSettingsRouteRoute,
  } as any)

const AdminConsoleSettingsDisplayRoute =
  AdminConsoleSettingsDisplayImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AdminConsoleSettingsRouteRoute,
  } as any)

const AdminConsoleSettingsAppearanceRoute =
  AdminConsoleSettingsAppearanceImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AdminConsoleSettingsRouteRoute,
  } as any)

const AdminConsoleSettingsAccountRoute =
  AdminConsoleSettingsAccountImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AdminConsoleSettingsRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRoute
    }
    '/_admin-console': {
      id: '/_admin-console'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminConsoleRouteImport
      parentRoute: typeof rootRoute
    }
    '/_website': {
      id: '/_website'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRoute
    }
    '/_admin-console/settings': {
      id: '/_admin-console/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminConsoleSettingsRouteImport
      parentRoute: typeof AdminConsoleRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpImport
      parentRoute: typeof authRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503Import
      parentRoute: typeof rootRoute
    }
    '/_website/': {
      id: '/_website/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WebsiteIndexImport
      parentRoute: typeof WebsiteRouteImport
    }
    '/_admin-console/settings/account': {
      id: '/_admin-console/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AdminConsoleSettingsAccountImport
      parentRoute: typeof AdminConsoleSettingsRouteImport
    }
    '/_admin-console/settings/appearance': {
      id: '/_admin-console/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AdminConsoleSettingsAppearanceImport
      parentRoute: typeof AdminConsoleSettingsRouteImport
    }
    '/_admin-console/settings/display': {
      id: '/_admin-console/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AdminConsoleSettingsDisplayImport
      parentRoute: typeof AdminConsoleSettingsRouteImport
    }
    '/_admin-console/settings/notifications': {
      id: '/_admin-console/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AdminConsoleSettingsNotificationsImport
      parentRoute: typeof AdminConsoleSettingsRouteImport
    }
    '/(auth)/forgot-password/': {
      id: '/(auth)/forgot-password/'
      path: '/'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof authForgotPasswordIndexImport
      parentRoute: typeof authForgotPasswordImport
    }
    '/(auth)/otp/': {
      id: '/(auth)/otp/'
      path: '/'
      fullPath: '/otp/'
      preLoaderRoute: typeof authOtpIndexImport
      parentRoute: typeof authOtpImport
    }
    '/(auth)/sign-in/': {
      id: '/(auth)/sign-in/'
      path: '/'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof authSignInIndexImport
      parentRoute: typeof authSignInImport
    }
    '/(auth)/sign-up/': {
      id: '/(auth)/sign-up/'
      path: '/'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof authSignUpIndexImport
      parentRoute: typeof authSignUpImport
    }
    '/_admin-console/apps/': {
      id: '/_admin-console/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AdminConsoleAppsIndexImport
      parentRoute: typeof AdminConsoleRouteImport
    }
    '/_admin-console/chats/': {
      id: '/_admin-console/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AdminConsoleChatsIndexImport
      parentRoute: typeof AdminConsoleRouteImport
    }
    '/_admin-console/dashboard/': {
      id: '/_admin-console/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminConsoleDashboardIndexImport
      parentRoute: typeof AdminConsoleRouteImport
    }
    '/_admin-console/help-center/': {
      id: '/_admin-console/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AdminConsoleHelpCenterIndexImport
      parentRoute: typeof AdminConsoleRouteImport
    }
    '/_admin-console/settings/': {
      id: '/_admin-console/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AdminConsoleSettingsIndexImport
      parentRoute: typeof AdminConsoleSettingsRouteImport
    }
    '/_admin-console/tasks/': {
      id: '/_admin-console/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AdminConsoleTasksIndexImport
      parentRoute: typeof AdminConsoleRouteImport
    }
    '/_admin-console/users/': {
      id: '/_admin-console/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminConsoleUsersIndexImport
      parentRoute: typeof AdminConsoleRouteImport
    }
    '/_website/about/': {
      id: '/_website/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof WebsiteAboutIndexImport
      parentRoute: typeof WebsiteRouteImport
    }
    '/_website/blog/': {
      id: '/_website/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof WebsiteBlogIndexImport
      parentRoute: typeof WebsiteRouteImport
    }
    '/_website/donation/': {
      id: '/_website/donation/'
      path: '/donation'
      fullPath: '/donation'
      preLoaderRoute: typeof WebsiteDonationIndexImport
      parentRoute: typeof WebsiteRouteImport
    }
    '/_website/dream/': {
      id: '/_website/dream/'
      path: '/dream'
      fullPath: '/dream'
      preLoaderRoute: typeof WebsiteDreamIndexImport
      parentRoute: typeof WebsiteRouteImport
    }
    '/_website/event/': {
      id: '/_website/event/'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof WebsiteEventIndexImport
      parentRoute: typeof WebsiteRouteImport
    }
  }
}

// Create and export the route tree

interface authForgotPasswordRouteChildren {
  authForgotPasswordIndexRoute: typeof authForgotPasswordIndexRoute
}

const authForgotPasswordRouteChildren: authForgotPasswordRouteChildren = {
  authForgotPasswordIndexRoute: authForgotPasswordIndexRoute,
}

const authForgotPasswordRouteWithChildren =
  authForgotPasswordRoute._addFileChildren(authForgotPasswordRouteChildren)

interface authOtpRouteChildren {
  authOtpIndexRoute: typeof authOtpIndexRoute
}

const authOtpRouteChildren: authOtpRouteChildren = {
  authOtpIndexRoute: authOtpIndexRoute,
}

const authOtpRouteWithChildren =
  authOtpRoute._addFileChildren(authOtpRouteChildren)

interface authSignInRouteChildren {
  authSignInIndexRoute: typeof authSignInIndexRoute
}

const authSignInRouteChildren: authSignInRouteChildren = {
  authSignInIndexRoute: authSignInIndexRoute,
}

const authSignInRouteWithChildren = authSignInRoute._addFileChildren(
  authSignInRouteChildren,
)

interface authSignUpRouteChildren {
  authSignUpIndexRoute: typeof authSignUpIndexRoute
}

const authSignUpRouteChildren: authSignUpRouteChildren = {
  authSignUpIndexRoute: authSignUpIndexRoute,
}

const authSignUpRouteWithChildren = authSignUpRoute._addFileChildren(
  authSignUpRouteChildren,
)

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRouteWithChildren
  authOtpRoute: typeof authOtpRouteWithChildren
  authSignInRoute: typeof authSignInRouteWithChildren
  authSignUpRoute: typeof authSignUpRouteWithChildren
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRouteWithChildren,
  authOtpRoute: authOtpRouteWithChildren,
  authSignInRoute: authSignInRouteWithChildren,
  authSignUpRoute: authSignUpRouteWithChildren,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AdminConsoleSettingsRouteRouteChildren {
  AdminConsoleSettingsAccountRoute: typeof AdminConsoleSettingsAccountRoute
  AdminConsoleSettingsAppearanceRoute: typeof AdminConsoleSettingsAppearanceRoute
  AdminConsoleSettingsDisplayRoute: typeof AdminConsoleSettingsDisplayRoute
  AdminConsoleSettingsNotificationsRoute: typeof AdminConsoleSettingsNotificationsRoute
  AdminConsoleSettingsIndexRoute: typeof AdminConsoleSettingsIndexRoute
}

const AdminConsoleSettingsRouteRouteChildren: AdminConsoleSettingsRouteRouteChildren =
  {
    AdminConsoleSettingsAccountRoute: AdminConsoleSettingsAccountRoute,
    AdminConsoleSettingsAppearanceRoute: AdminConsoleSettingsAppearanceRoute,
    AdminConsoleSettingsDisplayRoute: AdminConsoleSettingsDisplayRoute,
    AdminConsoleSettingsNotificationsRoute:
      AdminConsoleSettingsNotificationsRoute,
    AdminConsoleSettingsIndexRoute: AdminConsoleSettingsIndexRoute,
  }

const AdminConsoleSettingsRouteRouteWithChildren =
  AdminConsoleSettingsRouteRoute._addFileChildren(
    AdminConsoleSettingsRouteRouteChildren,
  )

interface AdminConsoleRouteRouteChildren {
  AdminConsoleSettingsRouteRoute: typeof AdminConsoleSettingsRouteRouteWithChildren
  AdminConsoleAppsIndexRoute: typeof AdminConsoleAppsIndexRoute
  AdminConsoleChatsIndexRoute: typeof AdminConsoleChatsIndexRoute
  AdminConsoleDashboardIndexRoute: typeof AdminConsoleDashboardIndexRoute
  AdminConsoleHelpCenterIndexRoute: typeof AdminConsoleHelpCenterIndexRoute
  AdminConsoleTasksIndexRoute: typeof AdminConsoleTasksIndexRoute
  AdminConsoleUsersIndexRoute: typeof AdminConsoleUsersIndexRoute
}

const AdminConsoleRouteRouteChildren: AdminConsoleRouteRouteChildren = {
  AdminConsoleSettingsRouteRoute: AdminConsoleSettingsRouteRouteWithChildren,
  AdminConsoleAppsIndexRoute: AdminConsoleAppsIndexRoute,
  AdminConsoleChatsIndexRoute: AdminConsoleChatsIndexRoute,
  AdminConsoleDashboardIndexRoute: AdminConsoleDashboardIndexRoute,
  AdminConsoleHelpCenterIndexRoute: AdminConsoleHelpCenterIndexRoute,
  AdminConsoleTasksIndexRoute: AdminConsoleTasksIndexRoute,
  AdminConsoleUsersIndexRoute: AdminConsoleUsersIndexRoute,
}

const AdminConsoleRouteRouteWithChildren =
  AdminConsoleRouteRoute._addFileChildren(AdminConsoleRouteRouteChildren)

interface WebsiteRouteRouteChildren {
  WebsiteIndexRoute: typeof WebsiteIndexRoute
  WebsiteAboutIndexRoute: typeof WebsiteAboutIndexRoute
  WebsiteBlogIndexRoute: typeof WebsiteBlogIndexRoute
  WebsiteDonationIndexRoute: typeof WebsiteDonationIndexRoute
  WebsiteDreamIndexRoute: typeof WebsiteDreamIndexRoute
  WebsiteEventIndexRoute: typeof WebsiteEventIndexRoute
}

const WebsiteRouteRouteChildren: WebsiteRouteRouteChildren = {
  WebsiteIndexRoute: WebsiteIndexRoute,
  WebsiteAboutIndexRoute: WebsiteAboutIndexRoute,
  WebsiteBlogIndexRoute: WebsiteBlogIndexRoute,
  WebsiteDonationIndexRoute: WebsiteDonationIndexRoute,
  WebsiteDreamIndexRoute: WebsiteDreamIndexRoute,
  WebsiteEventIndexRoute: WebsiteEventIndexRoute,
}

const WebsiteRouteRouteWithChildren = WebsiteRouteRoute._addFileChildren(
  WebsiteRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof WebsiteIndexRoute
  '': typeof WebsiteRouteRouteWithChildren
  '/settings': typeof AdminConsoleSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRouteWithChildren
  '/otp': typeof authOtpRouteWithChildren
  '/sign-in': typeof authSignInRouteWithChildren
  '/sign-up': typeof authSignUpRouteWithChildren
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/settings/account': typeof AdminConsoleSettingsAccountRoute
  '/settings/appearance': typeof AdminConsoleSettingsAppearanceRoute
  '/settings/display': typeof AdminConsoleSettingsDisplayRoute
  '/settings/notifications': typeof AdminConsoleSettingsNotificationsRoute
  '/forgot-password/': typeof authForgotPasswordIndexRoute
  '/otp/': typeof authOtpIndexRoute
  '/sign-in/': typeof authSignInIndexRoute
  '/sign-up/': typeof authSignUpIndexRoute
  '/apps': typeof AdminConsoleAppsIndexRoute
  '/chats': typeof AdminConsoleChatsIndexRoute
  '/dashboard': typeof AdminConsoleDashboardIndexRoute
  '/help-center': typeof AdminConsoleHelpCenterIndexRoute
  '/settings/': typeof AdminConsoleSettingsIndexRoute
  '/tasks': typeof AdminConsoleTasksIndexRoute
  '/users': typeof AdminConsoleUsersIndexRoute
  '/about': typeof WebsiteAboutIndexRoute
  '/blog': typeof WebsiteBlogIndexRoute
  '/donation': typeof WebsiteDonationIndexRoute
  '/dream': typeof WebsiteDreamIndexRoute
  '/event': typeof WebsiteEventIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof WebsiteIndexRoute
  '': typeof AdminConsoleRouteRouteWithChildren
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/settings/account': typeof AdminConsoleSettingsAccountRoute
  '/settings/appearance': typeof AdminConsoleSettingsAppearanceRoute
  '/settings/display': typeof AdminConsoleSettingsDisplayRoute
  '/settings/notifications': typeof AdminConsoleSettingsNotificationsRoute
  '/forgot-password': typeof authForgotPasswordIndexRoute
  '/otp': typeof authOtpIndexRoute
  '/sign-in': typeof authSignInIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
  '/apps': typeof AdminConsoleAppsIndexRoute
  '/chats': typeof AdminConsoleChatsIndexRoute
  '/dashboard': typeof AdminConsoleDashboardIndexRoute
  '/help-center': typeof AdminConsoleHelpCenterIndexRoute
  '/settings': typeof AdminConsoleSettingsIndexRoute
  '/tasks': typeof AdminConsoleTasksIndexRoute
  '/users': typeof AdminConsoleUsersIndexRoute
  '/about': typeof WebsiteAboutIndexRoute
  '/blog': typeof WebsiteBlogIndexRoute
  '/donation': typeof WebsiteDonationIndexRoute
  '/dream': typeof WebsiteDreamIndexRoute
  '/event': typeof WebsiteEventIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/_admin-console': typeof AdminConsoleRouteRouteWithChildren
  '/_website': typeof WebsiteRouteRouteWithChildren
  '/_admin-console/settings': typeof AdminConsoleSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRouteWithChildren
  '/(auth)/otp': typeof authOtpRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRouteWithChildren
  '/(auth)/sign-up': typeof authSignUpRouteWithChildren
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_website/': typeof WebsiteIndexRoute
  '/_admin-console/settings/account': typeof AdminConsoleSettingsAccountRoute
  '/_admin-console/settings/appearance': typeof AdminConsoleSettingsAppearanceRoute
  '/_admin-console/settings/display': typeof AdminConsoleSettingsDisplayRoute
  '/_admin-console/settings/notifications': typeof AdminConsoleSettingsNotificationsRoute
  '/(auth)/forgot-password/': typeof authForgotPasswordIndexRoute
  '/(auth)/otp/': typeof authOtpIndexRoute
  '/(auth)/sign-in/': typeof authSignInIndexRoute
  '/(auth)/sign-up/': typeof authSignUpIndexRoute
  '/_admin-console/apps/': typeof AdminConsoleAppsIndexRoute
  '/_admin-console/chats/': typeof AdminConsoleChatsIndexRoute
  '/_admin-console/dashboard/': typeof AdminConsoleDashboardIndexRoute
  '/_admin-console/help-center/': typeof AdminConsoleHelpCenterIndexRoute
  '/_admin-console/settings/': typeof AdminConsoleSettingsIndexRoute
  '/_admin-console/tasks/': typeof AdminConsoleTasksIndexRoute
  '/_admin-console/users/': typeof AdminConsoleUsersIndexRoute
  '/_website/about/': typeof WebsiteAboutIndexRoute
  '/_website/blog/': typeof WebsiteBlogIndexRoute
  '/_website/donation/': typeof WebsiteDonationIndexRoute
  '/_website/dream/': typeof WebsiteDreamIndexRoute
  '/_website/event/': typeof WebsiteEventIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/forgot-password/'
    | '/otp/'
    | '/sign-in/'
    | '/sign-up/'
    | '/apps'
    | '/chats'
    | '/dashboard'
    | '/help-center'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/about'
    | '/blog'
    | '/donation'
    | '/dream'
    | '/event'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/apps'
    | '/chats'
    | '/dashboard'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/about'
    | '/blog'
    | '/donation'
    | '/dream'
    | '/event'
  id:
    | '__root__'
    | '/(auth)'
    | '/_admin-console'
    | '/_website'
    | '/_admin-console/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_website/'
    | '/_admin-console/settings/account'
    | '/_admin-console/settings/appearance'
    | '/_admin-console/settings/display'
    | '/_admin-console/settings/notifications'
    | '/(auth)/forgot-password/'
    | '/(auth)/otp/'
    | '/(auth)/sign-in/'
    | '/(auth)/sign-up/'
    | '/_admin-console/apps/'
    | '/_admin-console/chats/'
    | '/_admin-console/dashboard/'
    | '/_admin-console/help-center/'
    | '/_admin-console/settings/'
    | '/_admin-console/tasks/'
    | '/_admin-console/users/'
    | '/_website/about/'
    | '/_website/blog/'
    | '/_website/donation/'
    | '/_website/dream/'
    | '/_website/event/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  AdminConsoleRouteRoute: typeof AdminConsoleRouteRouteWithChildren
  WebsiteRouteRoute: typeof WebsiteRouteRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  AdminConsoleRouteRoute: AdminConsoleRouteRouteWithChildren,
  WebsiteRouteRoute: WebsiteRouteRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(auth)",
        "/_admin-console",
        "/_website",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503"
      ]
    },
    "/(auth)": {
      "filePath": "(auth)/route.tsx",
      "children": [
        "/(auth)/forgot-password",
        "/(auth)/otp",
        "/(auth)/sign-in",
        "/(auth)/sign-up"
      ]
    },
    "/_admin-console": {
      "filePath": "_admin-console/route.tsx",
      "children": [
        "/_admin-console/settings",
        "/_admin-console/apps/",
        "/_admin-console/chats/",
        "/_admin-console/dashboard/",
        "/_admin-console/help-center/",
        "/_admin-console/tasks/",
        "/_admin-console/users/"
      ]
    },
    "/_website": {
      "filePath": "_website/route.tsx",
      "children": [
        "/_website/",
        "/_website/about/",
        "/_website/blog/",
        "/_website/donation/",
        "/_website/dream/",
        "/_website/event/"
      ]
    },
    "/_admin-console/settings": {
      "filePath": "_admin-console/settings/route.tsx",
      "parent": "/_admin-console",
      "children": [
        "/_admin-console/settings/account",
        "/_admin-console/settings/appearance",
        "/_admin-console/settings/display",
        "/_admin-console/settings/notifications",
        "/_admin-console/settings/"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.tsx",
      "parent": "/(auth)",
      "children": [
        "/(auth)/forgot-password/"
      ]
    },
    "/(auth)/otp": {
      "filePath": "(auth)/otp.tsx",
      "parent": "/(auth)",
      "children": [
        "/(auth)/otp/"
      ]
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx",
      "parent": "/(auth)",
      "children": [
        "/(auth)/sign-in/"
      ]
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.tsx",
      "parent": "/(auth)",
      "children": [
        "/(auth)/sign-up/"
      ]
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.tsx"
    },
    "/_website/": {
      "filePath": "_website/index.tsx",
      "parent": "/_website"
    },
    "/_admin-console/settings/account": {
      "filePath": "_admin-console/settings/account.tsx",
      "parent": "/_admin-console/settings"
    },
    "/_admin-console/settings/appearance": {
      "filePath": "_admin-console/settings/appearance.tsx",
      "parent": "/_admin-console/settings"
    },
    "/_admin-console/settings/display": {
      "filePath": "_admin-console/settings/display.tsx",
      "parent": "/_admin-console/settings"
    },
    "/_admin-console/settings/notifications": {
      "filePath": "_admin-console/settings/notifications.tsx",
      "parent": "/_admin-console/settings"
    },
    "/(auth)/forgot-password/": {
      "filePath": "(auth)/forgot-password/index.tsx",
      "parent": "/(auth)/forgot-password"
    },
    "/(auth)/otp/": {
      "filePath": "(auth)/otp/index.tsx",
      "parent": "/(auth)/otp"
    },
    "/(auth)/sign-in/": {
      "filePath": "(auth)/sign-in/index.tsx",
      "parent": "/(auth)/sign-in"
    },
    "/(auth)/sign-up/": {
      "filePath": "(auth)/sign-up/index.tsx",
      "parent": "/(auth)/sign-up"
    },
    "/_admin-console/apps/": {
      "filePath": "_admin-console/apps/index.tsx",
      "parent": "/_admin-console"
    },
    "/_admin-console/chats/": {
      "filePath": "_admin-console/chats/index.tsx",
      "parent": "/_admin-console"
    },
    "/_admin-console/dashboard/": {
      "filePath": "_admin-console/dashboard/index.tsx",
      "parent": "/_admin-console"
    },
    "/_admin-console/help-center/": {
      "filePath": "_admin-console/help-center/index.tsx",
      "parent": "/_admin-console"
    },
    "/_admin-console/settings/": {
      "filePath": "_admin-console/settings/index.tsx",
      "parent": "/_admin-console/settings"
    },
    "/_admin-console/tasks/": {
      "filePath": "_admin-console/tasks/index.tsx",
      "parent": "/_admin-console"
    },
    "/_admin-console/users/": {
      "filePath": "_admin-console/users/index.tsx",
      "parent": "/_admin-console"
    },
    "/_website/about/": {
      "filePath": "_website/about/index.tsx",
      "parent": "/_website"
    },
    "/_website/blog/": {
      "filePath": "_website/blog/index.tsx",
      "parent": "/_website"
    },
    "/_website/donation/": {
      "filePath": "_website/donation/index.tsx",
      "parent": "/_website"
    },
    "/_website/dream/": {
      "filePath": "_website/dream/index.tsx",
      "parent": "/_website"
    },
    "/_website/event/": {
      "filePath": "_website/event/index.tsx",
      "parent": "/_website"
    }
  }
}
ROUTE_MANIFEST_END */
